services:
  zm.ratelimiter.api:
    image: ${DOCKER_REGISTRY-}zmratelimiterapi
    build:
      context: .
      dockerfile: src/ZM.RateLimiter.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:9000
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - proxybackend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisvolume:/data
    networks:
      - proxybackend

networks:
  proxybackend:
    name: proxybackend

volumes:
  redisvolume:
